export interface IBase {
  id: number;
  created_at: string;
}

/**
 * User Entity
 */
export interface IUser extends IBase {
  username: string;
  email: string;
  password_hash: string;
  bio?: string | null;
  avatar_url?: string | null;
  is_online: boolean;
}

/**
 * Post Entity
 */
export interface IPost extends IBase {
  user_id: number;
  content: string;
  image_url?: string | null;
}

export interface IPostResponse extends IPost {
  comments_count: number;
  likes_count: number;
}

/**
 * Comment Entity
 */
export interface IComment extends IBase {
  user_id: number;
  post_id: number;
  content: string;
}

/**
 * Like Entity
 */
export interface ILike extends IBase {
  user_id: number;
  post_id: number;
}

/**
 * Follow Entity
 */
export interface IFollow extends IBase {
  follower_id: number;
  following_id: number;
}

// --- Utility Types for API Requests ---

// Used when creating a new post (id and created_at are generated by DB)
export type CreatePostInput = Omit<IPost, "id" | "created_at">;

// Used when a user registers
export type RegisterUserInput = Omit<IUser, "id" | "created_at">;

// Used when sending a user profile to the frontend (Security: remove password_hash)
export type UserProfileResponse = Omit<IUser, "password_hash">;
